name: Deploy LinkTag

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Create and rename JAR file
        run: |
          ./gradlew bootJar
          mv build/libs/linktag-*.jar linktag.jar

      - name: Copy JAR file to the server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: linktag.jar
          target: /opt/linktag/

      - name: Restart Spring Boot service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sudo systemctl restart linktag.service
